---
title: "Data_analyse"
author: "Astrid Elmann"
date: "1/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, readbulk, wesanderson, lmerTest)
```

```{r}
# load data
with_errors <- read_csv("clean_data.csv",
              col_names = TRUE,
              col_types = cols(
                timestamp = "c", 
                experiment_ID = "f", 
                subject = "f",
                r_len = "n",
                handedness = "f",
                vision = "f",
                colorvision = "f",
                age = "c", #@ fix this
                gender = "f",
                nationality = "f",
                r_type = "f",
                IOS = "f", 
                key_press = "f",
                rt = "n",
                trial_stim = "f",
                congruency = "f",
                accuracy = "f"
              ))
```

```{r}
# remove error and neutral trials
d <- with_errors %>% 
  filter(accuracy == "correct") %>% 
  filter(congruency != "neutral")
```

# Sirid code
```{r}
# getting a nice Wes Anderson color palette

# I like this one
#wes_palette('Darjeeling1')

# save it in a variable to be used when plotting
pal <- wes_palettes$Darjeeling1
```

### Plot mean RT with SE errorbars
```{r}
with_errors %>% 
  filter(
    accuracy == 'correct'
    ) %>% 
ggplot() + 
  aes(x = congruency, y = rt, color = congruency) +
  # creating the geom points of the mean rt of  each congruency
  stat_summary(fun = "mean", geom = "point", size = 3, color = pal[1:3]) +
  # adding the error bars
  stat_summary(fun.data = "mean_se", geom = "errorbar", width = .1, color = pal[1:3]) +
  # adding the connecting line between the points 
  stat_summary(fun = 'mean', geom = 'line', color = pal[5], aes(group = 1)) +
  theme(legend.position = 'None') +
  labs(title = 'Mean RT of the Simon Task with SE errorbars')
```

### Visualize the accuracy for each congruency
```{r}
with_errors %>% 
  ggplot() +
  aes(accuracy, fill = congruency) + 
  geom_bar() + 
  facet_grid(~ congruency) +
  scale_fill_manual(values = pal) +
  labs(title = 'Accuracy for each congruency') + 
  theme(legend.position = 'NULL')
```


### Model rt ~ congruency 
```{r}
m1 <- lmerTest::lmer(rt ~ congruency + (1|subject), d)
summary(m1)
```

### Model rt ~ congruency + IOS + subject
```{r}
m1 <- lmerTest::lmer(rt ~ congruency + (1|IOS) + (1|subject), d)
summary(m1)
```

```{r}
# Compute the analysis of variance
res.aov <- aov(weight ~ group, data = my_data)
# Summary of the analysis
summary(res.aov)
```


